### ISSUE TITLE
Road to 2.5

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk-docker#14]
This issue serves as the epic for the ongoing work towards the Zephyr 2.5.0 upgrade.

- [x] fix `curl` dependency conflict (https://github.com/zmkfirmware/zmk-docker/pull/13)
- [x] fix `ARG REPOSITORY_URL=https://github.com/innovaker/zmk-docker`
- [x] fix dependabot's builds (https://github.com/zmkfirmware/zmk-docker/pull/12)
- [x] re-trigger dependabot's bumped candidate
  - [x] test `zmk-dev-arm`
  - [x] test `zmk-build-arm`
  - [x] merge
- [x] set `LESS` as pager (https://github.com/zmkfirmware/zmk-docker/pull/1) via adoption workflow
  - [x] test `zmk-dev-arm`
- [x] investigate adding gdb (https://github.com/zmkfirmware/zmk-docker/issues/7) ... if time allows
  - [x] test `zmk-dev-arm`
- [x] bump (and tag?) Zephyr SDK to each non-beta version since `0.11.4` but only with basic ci testing
   - so we have intermediate images for regression testing if needed
- [x] compare installation instructions for 2.5.0 with Dockerfile (especially apt dependencies)
- [x] bump Zephyr to 2.5.0 and synchronize any installation changes
  - [x] test `zmk-build-arm` (via hash tag in https://github.com/zmkfirmware/zmk/pull/736)
  - [x] test `zmk-dev-arm` (via hash tag in https://github.com/zmkfirmware/zmk/pull/736)
- [x] tag (release) `2.5.0-x.y.z` and `2.5`

**Comment by innovaker** [comment]
These would also be useful but are unlikely to be tackled before 2.5:
- [x] find solution for security constraints around non-dependabot PRs
- [x] integrate ZMK test build into container workflow

**Comment by mcrosson** [comment]
will open PRs be merged / included via some means along the path?

**Comment by innovaker** [comment]
List from Discord:
https://discord.com/channels/719497620560543766/719544230497878116/854074340542513172
- [x] Point `zmk-docker` fork at zmkfirmware/zmk#736 using `ZMK_REPOSITORY` and `ZMK_REF` secrets.
- [x] Push `feat/zephyr-2.5.0` branch to trigger rebuild within fork.
- [x] Check integration tests pass.
- [x] Create Zephyr 2.5.0 PR (#78).
- [x] Merge Zephyr 2.5.0 PR (#78).
- [x] In the ZMK 2.5 PR (zmkfirmware/zmk#736), change (3x) image references to point at the candidate image.
- [x] Test candidate locally (devices etc.).
- [x] Release the candidate.
- [x] Update ZMK 2.5 PR (zmkfirmware/zmk#736) image references to `2.5`.
- [ ] Merge ZMK 2.5 PR (zmkfirmware/zmk#736).

**Comment by innovaker** [comment]
Note, full unit tests (`RUN_UNIT_TESTS`) passed but the jobs failed because the `zmk-build-xxx` containers didn't seem to stop.

**Comment by innovaker** [comment]
And of course, let's not forget ...
- [x] Switch default branch to `2.5-branch`.
